In [9]:
import numpy as np 
import pandas as pd

**Creating a DataFrame**

In [5]:
import numpy as np 
import pandas as pd 

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

# pd.DataFrame(data)

# df = pd.DataFrame(data)

# print(df)

# pd.DataFrame(data)

# df = pd.DataFrame(data)

# print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [51]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]



# df2 = pd.DataFrame(data_list)
# columns = ["Name","Age","City","Salary"]
# df2 = pd.DataFrame(data_list,columns =columns)
# df2

# df2 = pd.DataFrame(data_list)
# print(df2)

# columns = ["Name", "Age","City","salary"]

# df2 = pd.DataFrame(data_list,columns=columns)

# print(df2)

# df2 = pd.DataFrame(data_list)

columns = ["Name" , "Age" , "City" , "Salary"]

df_2 = pd.DataFrame(data_list , columns = columns )

df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df_2["Name"]
df_2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

**Selection and Indexing of Columns**

In [21]:
df_2[["Name" , "City"]]

df_2[["Salary", "City"]]

   Salary      City
0   65000  New York
1   70000     Paris
2   62000    Berlin
3   85000    London

In [20]:
# df2[["Name","City"]]

# df2[["Name","City"]]

# df2[["Age","salary"]]

   Age  salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

**Creating a new column**

In [25]:
# df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

# df2["Designation"] = ["Doc","Eng.","Doc","Eng."]

df_2["Designation"] = ["DOC","Eng.","DOC","ENG."]

In [26]:
df_2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         DOC
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000         DOC
3  Linda   42    London   85000        ENG.

**Removing Columns**

In [47]:
# df2.drop(0,axis = 0)

# df2.drop("Designation",axis=1)

# df2.drop("Designation",axis=1,inplace=True)

# df2.drop(["City","salary"],axis=1)

# df2.drop(0,axis=0)

# df_2.drop("Designation", axis=1)

df_2

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [41]:

df_2

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

**Selecting Rows**

In [48]:
df2

SyntaxError: invalid syntax (2131019865.py, line 1)

In [64]:
# df2.loc[[0,1]]

# df_2.loc[[0,1,2]]

df_2


df_2.loc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [60]:
# df.iloc[3]

# df.iloc[3]

df.iloc[3,2]

'London'

**Selecting Subsets of Rows and Columns**

In [56]:
# df.loc[[0,1]][["City","Salary"]]

# df.loc[[0,1]][["City","Salary"]]

df.loc[[0,1,3]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000
3    London   85000

In [65]:
# df.loc[[2,3]][["Name","Age"]]

df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection**

In [67]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [72]:
#I only want to see those people whose age is above 30

# df_2[df_2["Age"] > 30]

df_2[df_2["Salary"] > 70000]

    Name  Age    City  Salary
3  Linda   42  London   85000

In [72]:
# df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#I only want poeple whose age is above 30 and their city must be paris

In [74]:
# df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

df_2[(df_2["Age"]>  30 ) & (df_2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000